In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from keras.utils import np_utils
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten





Using TensorFlow backend.


In [ ]:
data_xy = np.load('train_xy.npy')

In [ ]:
label_xy = np.load('train_label_xy.npy')


In [ ]:
data_xy = data_xy.reshape(167,6,3136)
label_xy = label_xy.reshape(167,6,)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_xy, label_xy, test_size = 0.2, random_state = 0)

In [ ]:
X_train = X_train.reshape(X_train.shape[0]*6, 3136)
y_train = y_train.reshape(y_train.shape[0]*6,)

X_test = X_test.reshape(X_test.shape[0]*6, 3136)
y_test = y_test.reshape(y_test.shape[0]*6,)

In [ ]:
img_rows, img_cols = 56, 56  

In [ ]:
X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols,1)
X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols,1)
input_shape = (img_rows, img_cols, 1)
    
    


In [ ]:
X_train.shape

(798, 56, 56, 1)

In [ ]:
y_train.shape

(798,)

In [ ]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
#y_train = np_utils.to_categorical(y_train, 2)
#y_test = np_utils.to_categorical(y_test, 2)




In [ ]:
X_train.shape

(798, 56, 56, 1)

In [ ]:
y_train.shape

(798,)

In [ ]:
X_test.shape

(204, 56, 56, 1)

In [ ]:
y_test.shape

(204,)

In [ ]:
import os
import datetime
logdir = os.path.join("logs", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)

In [ ]:
cnn =tf.keras.models.Sequential()

In [ ]:
cnn.add(tf.keras.layers.Conv2D(filters = 32, kernel_size = (3,3), activation ='relu', input_shape = input_shape))
cnn.add(tf.keras.layers.MaxPooling2D(pool_size = 2, strides = 2))
cnn.add((tf.keras.layers.Dropout(0.2)))


In [ ]:
cnn.add(tf.keras.layers.Conv2D(filters = 64, kernel_size = (3,3), activation ='relu'))
cnn.add(tf.keras.layers.MaxPooling2D(pool_size = 2, strides = 2))
cnn.add((tf.keras.layers.Dropout(0.2)))


In [ ]:
cnn.add(tf.keras.layers.Conv2D(filters = 128, kernel_size = (3,3), activation ='relu'))
cnn.add(tf.keras.layers.MaxPooling2D(pool_size = 2, strides = 2))
cnn.add((tf.keras.layers.Dropout(0.2)))


In [ ]:
cnn.add(tf.keras.layers.Flatten())

In [ ]:
cnn.add(tf.keras.layers.Dense(128, activation= 'relu'))

In [ ]:
cnn.add(tf.keras.layers.Dense(2, activation='softmax'))

In [ ]:
cnn.compile(optimizer= 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
cnn.fit(X_train, y_train, batch_size=128, epochs=15, validation_split=0.2, callbacks=[tensorboard_callback])
cnn.summary()

Epoch 1/15
5/5 [==============================] - 3s 553ms/step - loss: 0.8335 - accuracy: 0.4796 - val_loss: 0.6933 - val_accuracy: 0.5625
Epoch 2/15
5/5 [==============================] - 3s 515ms/step - loss: 0.6947 - accuracy: 0.5031 - val_loss: 0.6936 - val_accuracy: 0.4875
Epoch 3/15
5/5 [==============================] - 3s 515ms/step - loss: 0.6941 - accuracy: 0.5235 - val_loss: 0.6932 - val_accuracy: 0.4625
Epoch 4/15
5/5 [==============================] - 3s 517ms/step - loss: 0.6933 - accuracy: 0.4984 - val_loss: 0.6932 - val_accuracy: 0.5562
Epoch 5/15
5/5 [==============================] - 3s 515ms/step - loss: 0.6932 - accuracy: 0.4906 - val_loss: 0.6932 - val_accuracy: 0.5063
Epoch 6/15
5/5 [==============================] - 3s 513ms/step - loss: 0.6932 - accuracy: 0.4404 - val_loss: 0.6931 - val_accuracy: 0.5000
Epoch 7/15
5/5 [==============================] - 3s 512ms/step - loss: 0.6932 - accuracy: 0.4530 - val_loss: 0.6931 - val_accuracy: 0.4563
Epoch 8/15
5/5 [====

In [ ]:
evaluation = cnn.evaluate(X_test, y_test, batch_size=128, verbose=1)
print('Summary: Loss over the test dataset: %.2f, Testing Accuracy: %.2f' % (evaluation[0], evaluation[1]))

2/2 [==============================] - 0s 48ms/step - loss: 0.6931 - accuracy: 0.5343
Summary: Loss over the test dataset: 0.69, Testing Accuracy: 0.53


In [ ]:
y_pred = cnn.predict(X_test)

In [ ]:
y_pred.shape

(204, 2)

In [ ]:
y_pred


array([[0.49969485, 0.5003051 ],
       [0.49977607, 0.50022393],
       [0.49977502, 0.500225  ],
       [0.49991298, 0.500087  ],
       [0.49994877, 0.50005126],
       [0.4998236 , 0.5001764 ],
       [0.50035447, 0.49964547],
       [0.5009806 , 0.49901935],
       [0.5009691 , 0.49903083],
       [0.501751  , 0.49824905],
       [0.500584  , 0.49941596],
       [0.49994317, 0.50005686],
       [0.50030184, 0.49969813],
       [0.50017875, 0.49982128],
       [0.5001644 , 0.4998356 ],
       [0.5003135 , 0.49968645],
       [0.5001922 , 0.49980778],
       [0.50014794, 0.49985206],
       [0.5001714 , 0.49982852],
       [0.50017947, 0.4998206 ],
       [0.5002515 , 0.49974853],
       [0.50049865, 0.49950132],
       [0.5004851 , 0.49951485],
       [0.50015193, 0.49984813],
       [0.50039876, 0.4996012 ],
       [0.500681  , 0.4993191 ],
       [0.5007206 , 0.49927935],
       [0.5005792 , 0.4994208 ],
       [0.50038004, 0.49962002],
       [0.5003014 , 0.4996986 ],
       [0.

In [ ]:
y_test.shape

(204,)

In [ ]:
y_pred.argmax(axis=1)

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred.argmax(axis=1))
print(cm)
accuracy_score(y_test, y_pred.argmax(axis= 1))

[[55 17]
 [78 54]]


0.5343137254901961